import {
  Body,
  Button,
  Container,
  Head,
  Heading,
  Html,
  Preview,
  Text,
} from "@react-email/components";

// Brand colors — inlined per component since email clients strip <style>
// blocks and don't support CSS variables or @font-face reliably.
const COLOR_NAVY = "#0C2142";
const COLOR_GOLD = "#D4A616";
const COLOR_CREAM = "#F5F0E6";

export interface VerifyEmailProps {
  /** The verification link, including token, generated by Better Auth. */
  url: string;
}

/**
 * Transactional email asking a new user to verify their email address.
 * @param props.url - the verification link to send the user to.
 * Why it exists: emailAndPassword.requireEmailVerification is enabled in
 * lib/auth.ts, so no one can sign in until they click this link.
 */
export default function VerifyEmail({ url }: VerifyEmailProps) {
  return (
    <Html>
      <Head />
      <Preview>Verify your email to finish setting up your Wangeci account</Preview>
      <Body style={{ backgroundColor: COLOR_CREAM, fontFamily: "Arial, Helvetica, sans-serif", margin: 0, padding: "32px 0" }}>
        <Container
          style={{
            backgroundColor: "#FFFFFF",
            borderRadius: "8px",
            margin: "0 auto",
            maxWidth: "480px",
            padding: "40px 32px",
          }}
        >
          <Heading style={{ color: COLOR_NAVY, fontSize: "22px", margin: "0 0 16px" }}>
            Verify your email
          </Heading>
          <Text style={{ color: COLOR_NAVY, fontSize: "15px", lineHeight: "24px", margin: "0 0 24px" }}>
            Thanks for signing up for Wangeci. Confirm this is your email address to
            activate your account and start reading.
          </Text>
          <Button
            href={url}
            style={{
              backgroundColor: COLOR_GOLD,
              borderRadius: "6px",
              color: COLOR_NAVY,
              display: "inline-block",
              fontSize: "15px",
              fontWeight: "bold",
              padding: "12px 28px",
              textDecoration: "none",
            }}
          >
            Verify email
          </Button>
          <Text style={{ color: COLOR_NAVY, fontSize: "13px", lineHeight: "20px", margin: "24px 0 0" }}>
            If the button above doesn't work, copy and paste this link into your
            browser:
          </Text>
          <Text style={{ color: COLOR_NAVY, fontSize: "13px", lineHeight: "20px", margin: "4px 0 0", wordBreak: "break-all" }}>
            {url}
          </Text>
          <Text style={{ color: "#6B7280", fontSize: "12px", lineHeight: "18px", margin: "32px 0 0" }}>
            If you didn't create a Wangeci account, you can safely ignore this email.
          </Text>
        </Container>
      </Body>
    </Html>
  );
}
